language: python
cache: pip
dist: xenial
python: 3.8

env:
  global:
    - PIP_UNSTABLE_FEATURE=

stages:
- primary
- secondary
- experimental

jobs:
  include:
    # Basic Checks
    - stage: primary
      env: NOXSESSION=primary

    # Complete checking for ensuring compatibility
    # PyPy
    - stage: secondary
      env: NOXSESSION=secondary
      python: pypy3.5-7.0.0

    # Test experimental stuff that are not part of the standard pip usage.
    # Helpful for developers working on them to see how they're doing.
    - stage: experimental
      env: NOXSESSION=experimental PIP_UNSTABLE_FEATURE=resolver GROUP=1
    - env: NOXSESSION=experimental PIP_UNSTABLE_FEATURE=resolver GROUP=2

  fast_finish: true
  allow_failures:
    - env: NOXSESSION=experimental PIP_UNSTABLE_FEATURE=resolver

install: pip install nox
script: nox
