language: python
cache: pip
python: 3.8

matrix:
  include:
    - env: NOXSESSION=docs
    - env: NOXSESSION=lint
    - python: 2.7
      env: NOXSESSION=tests-2.7
    - python: 3.4
      env: NOXSESSION=tests-3.4
    - python: 3.5
      env: NOXSESSION=tests-3.5
    - python: 3.6
      env: NOXSESSION=tests-3.6
    - python: 3.7
      env: NOXSESSION=tests-3.7
    - python: 3.8
      env: NOXSESSION=tests-3.8

install:
  - pip3 install nox

script:
  - python3 -m nox
