name: Test

on:
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - '**.py'
  push:
    paths:
      - '.github/workflows/test.yml'
      - '**.py'

jobs:
  test-cpython:
    name: CPython ${{ matrix.python_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        # Python 3.4 is not available from actions/setup-python@v1.
        python_version: ['2.7', '3.5', '3.6', '3.7', '3.8']

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      name: Install Python ${{ matrix.python_version }}
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install nox
      shell: bash

    - name: Run nox
      run: |
        nox -s tests-${{ matrix.python_version }}
      shell: bash
