name: Test

on:
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - '**.py'
  push:
    paths:
      - '.github/workflows/test.yml'
      - '**.py'

jobs:
  test-cpython:
    name: CPython ${{ matrix.python_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        # Python 3.4 is not available from actions/setup-python@v1.
        python_version: ['2.7', '3.5']

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      name: Install Python ${{ matrix.python_version }}
      with:
        python-version: ${{ matrix.python_version }}

    - uses: actions/setup-python@v1
      name: Install Python 3.x
      with:
        python-version: 3.x
      if: matrix.python_version == '2.7'

    # Work around https://github.com/theacodes/nox/issues/250
    - name: Python 2 on Windows workaround
      run: |
        Remove-Item C:\ProgramData\Chocolatey\bin\python2.7.exe
      shell: bash
      if: matrix.python_version == '2.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install nox
      shell: bash

    - name: Run nox
      run: |
        python -m nox -s tests-${{ matrix.python_version }}
      shell: bash
